// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompletedStepsController from "./completed_steps_controller.js"
application.register("completed-steps", CompletedStepsController)

import DocHighlightController from "./doc_highlight_controller.js"
application.register("doc-highlight", DocHighlightController)

import DragController from "./drag_controller.js"
application.register("drag", DragController)

import EditTasksController from "./edit_tasks_controller.js"
application.register("edit-tasks", EditTasksController)

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)

import NightController from "./night_controller.js"
application.register("night", NightController)

import NotificationBoxController from "./notification_box_controller.js"
application.register("notification-box", NotificationBoxController)

import NotificationSubscriptionController from "./notification_subscription_controller.js"
application.register("notification-subscription", NotificationSubscriptionController)

import ProjectsController from "./projects_controller.js"
application.register("projects", ProjectsController)
