meta_product_name: "Flipeasy"
meta_title: "Flipeasy - Manage your flips seamlessly"
meta_description: "With Flipeasy, you will love doing flips!"
# meta_image: "../assets/logo-rose"
# twitter_account: "@product_twitter_account"
